export type DiseaseReference = { label: string; url: string };
export type Disease = {
  id: number;
  name: string;
  scientificName: string;
  type: string; // فيروسي | بكتيري | طفيلي | فطري | استقلابي | عصبي | ...
  severity: 'منخفض' | 'متوسط' | 'عالي';
  description: string;
  symptoms: string[];
  treatment: string;
  prevention?: string;
  onset?: string;
  species: string[];
  references?: DiseaseReference[];
  image?: string;
};

// بيانات عربية افتراضية (حل دائم) تُستخدم عند غياب بيانات i18n.
// ملاحظة: الاسم العلمي يُترك بصيغته المتعارف عليها عالمياً (لاتيني/إنجليزي) لأنه معيار طبي.

export const COMMON_DISEASES_AR: Disease[] = [
  {
    id: 1,
    name: 'داء الكَلَب (السُّعار)',
    scientificName: 'Rabies virus infection',
    type: 'فيروسي',
    severity: 'عالي',
    description: 'مرض فيروسي قاتل ينتقل غالباً عبر العضّ ويؤثر على الجهاز العصبي. الوقاية بالتطعيم هي الأساس.',
    symptoms: ['تغيّر في السلوك', 'سلوك عدواني أو خوف شديد', 'سيلان لعاب', 'صعوبة بلع', 'شلل تدريجي', 'تشنجات'],
    treatment: 'لا يوجد علاج فعّال بعد ظهور الأعراض. يتم التركيز على الوقاية والتطعيم وإجراءات السلامة.',
    prevention: 'تطعيم دوري للحيوانات، تجنّب مخالطة الحيوانات الضالة، التوجه للطبيب فوراً بعد أي عضة.',
    onset: 'عادةً من أسابيع إلى أشهر بعد التعرض.',
    species: ['الكلاب', 'القطط', 'الحيوانات البرية'],
    references: [
      { label: 'WHO - Rabies', url: 'https://www.who.int/news-room/fact-sheets/detail/rabies' },
      { label: 'CDC - Rabies', url: 'https://www.cdc.gov/rabies/' },
    ],
  },
  {
    id: 2,
    name: 'ديستمبر الكلاب',
    scientificName: 'Canine distemper virus',
    type: 'فيروسي',
    severity: 'عالي',
    description: 'مرض فيروسي شديد العدوى يؤثر على الجهاز التنفسي والهضمي والعصبي لدى الكلاب.',
    symptoms: ['حمّى', 'إفرازات من العين والأنف', 'سعال', 'قيء/إسهال', 'خمول', 'تشنجات (في الحالات المتقدمة)'],
    treatment: 'علاج داعم (سوائل، أدوية للعدوى الثانوية، مضادات قيء) وفق إشراف بيطري. لا يوجد علاج نوعي للفيروس.',
    prevention: 'تطعيمات منتظمة (DHP/DA2PP)، عزل الحالات المشتبه بها، تعقيم البيئة.',
    onset: 'عادةً خلال 1–2 أسبوع من التعرض.',
    species: ['الكلاب'],
    references: [
      { label: 'Merck Vet Manual - Distemper', url: 'https://www.merckvetmanual.com/dog-owners/infectious-diseases-of-dogs/canine-distemper' },
    ],
  },
  {
    id: 3,
    name: 'بارفو الكلاب',
    scientificName: 'Canine parvovirus',
    type: 'فيروسي',
    severity: 'عالي',
    description: 'فيروس يسبب التهاباً شديداً في الأمعاء خاصة في الجراء مع خطر جفاف سريع.',
    symptoms: ['إسهال شديد (قد يكون دموي)', 'قيء', 'فقدان شهية', 'جفاف', 'خمول'],
    treatment: 'علاج داعم مكثف في العيادة (سوائل وريدية، مضادات قيء، مضادات حيوية عند الحاجة).',
    prevention: 'تطعيمات الجراء وفق الجدول، تعقيم قوي (هيبوكلوريت/كلور)، تجنب أماكن العدوى.',
    onset: '3–7 أيام غالباً بعد التعرض.',
    species: ['الكلاب'],
    references: [
      { label: 'AVMA - Canine Parvovirus', url: 'https://www.avma.org/resources/pet-owners/petcare/canine-parvovirus' },
    ],
  },
  {
    id: 4,
    name: 'التهاب الجلد الفطري (السعفة)',
    scientificName: 'Dermatophytosis (Ringworm)',
    type: 'فطري',
    severity: 'متوسط',
    description: 'عدوى فطرية جلدية شائعة قد تنتقل للبشر. تظهر كبقع دائرية مع تساقط شعر وحكة.',
    symptoms: ['بقع دائرية صلعاء', 'حكة', 'قشور', 'احمرار'],
    treatment: 'مضادات فطرية موضعية/فموية حسب الشدة + تعقيم البيئة وعزل الحيوان.',
    prevention: 'نظافة البيئة، فحص الحيوانات الجديدة، تعقيم الأدوات.',
    onset: 'أيام إلى أسابيع.',
    species: ['القطط', 'الكلاب', 'الأرانب'],
    references: [
      { label: 'Merck Vet Manual - Dermatophytosis', url: 'https://www.merckvetmanual.com/integumentary-system/dermatophytosis/dermatophytosis' },
    ],
  },
  {
    id: 5,
    name: 'التهاب الأذن الخارجية',
    scientificName: 'Otitis externa',
    type: 'التهابي',
    severity: 'متوسط',
    description: 'التهاب شائع في قناة الأذن نتيجة حساسية/فطريات/بكتيريا أو رطوبة زائدة.',
    symptoms: ['حكة بالأذن', 'هز الرأس', 'رائحة كريهة', 'إفرازات', 'ألم عند اللمس'],
    treatment: 'تنظيف الأذن بطريقة صحيحة + قطرات موضعية مضادة للميكروبات حسب التشخيص.',
    prevention: 'تجفيف الأذن بعد الاستحمام، علاج الحساسية، تنظيف دوري عند الحاجة.',
    onset: 'قد يكون حاداً أو مزمناً.',
    species: ['الكلاب', 'القطط'],
    references: [
      { label: 'Merck Vet Manual - Otitis Externa', url: 'https://www.merckvetmanual.com/ear-disorders/otitis-externa/otitis-externa-in-dogs-and-cats' },
    ],
  },
  {
    id: 6,
    name: 'حساسية الجلد/التهاب الجلد التحسّسي',
    scientificName: 'Allergic dermatitis',
    type: 'تحسّسي',
    severity: 'متوسط',
    description: 'تحسس من طعام/براغيث/عوامل بيئية يسبب حكة واحمراراً متكرراً.',
    symptoms: ['حكة', 'احمرار', 'لعق/قضم الجلد', 'التهاب أذن متكرر'],
    treatment: 'تحديد السبب + أدوية للحكة/الالتهاب + علاج البراغيث + حمية تجريبية إن لزم.',
    prevention: 'مكافحة البراغيث، تجنب المهيجات، متابعة غذائية.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 7,
    name: 'التهاب اللثة وأمراض الأسنان',
    scientificName: 'Periodontal disease',
    type: 'مزمن',
    severity: 'متوسط',
    description: 'تراكم جير والتهاب لثة يؤدي لرائحة فم ومضاعفات قد تؤثر على القلب والكلى.',
    symptoms: ['رائحة فم', 'نزف لثة', 'صعوبة مضغ', 'تساقط أسنان'],
    treatment: 'تنظيف أسنان لدى الطبيب + علاج التهابات + خطة عناية منزلية.',
    prevention: 'تفريش أسنان، ألعاب/علاجات أسنان، زيارات دورية.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 8,
    name: 'الجفاف',
    scientificName: 'Dehydration',
    type: 'استقلابي',
    severity: 'عالي',
    description: 'نقص سوائل الجسم نتيجة قيء/إسهال/حرارة أو قلة شرب وقد يصبح خطيراً بسرعة.',
    symptoms: ['خمول', 'جفاف لثة', 'عيون غائرة', 'قلة تبول', 'فقدان شهية'],
    treatment: 'تعويض سوائل (فموي/وريدي) ومعالجة السبب الأساسي.',
    prevention: 'ماء متاح دائماً، علاج مبكر للقيء/الإسهال، تجنب الحرارة.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 9,
    name: 'التهاب المعدة والأمعاء',
    scientificName: 'Gastroenteritis',
    type: 'هضمي',
    severity: 'متوسط',
    description: 'اضطراب هضمي شائع بسبب عدوى أو طعام غير مناسب أو جسم غريب.',
    symptoms: ['قيء', 'إسهال', 'ألم بطني', 'خمول'],
    treatment: 'صيام قصير بإشراف + سوائل + أدوية قيء/مضادات حسب الحالة.',
    prevention: 'منع القمامة/الأجسام الغريبة، طعام ثابت الجودة، تطعيمات.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 10,
    name: 'التهاب البنكرياس',
    scientificName: 'Pancreatitis',
    type: 'هضمي',
    severity: 'عالي',
    description: 'التهاب البنكرياس يسبب ألماً شديداً وقيئاً، وقد يحدث بعد أطعمة دسمة.',
    symptoms: ['قيء متكرر', 'ألم بطني', 'فقدان شهية', 'خمول'],
    treatment: 'سوائل وريدية، مسكنات، مضادات قيء، حمية قليلة الدهون وفق الطبيب.',
    prevention: 'تجنب الأطعمة الدسمة وبقايا الطعام، ضبط الوزن.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 11,
    name: 'التهاب المسالك البولية',
    scientificName: 'Urinary tract infection (UTI)',
    type: 'مسالك بولية',
    severity: 'متوسط',
    description: 'عدوى بكتيرية في الجهاز البولي قد تسبب ألماً وكثرة تبول.',
    symptoms: ['كثرة تبول', 'ألم عند التبول', 'بول دموي', 'تبول خارج الصندوق (للقطط)'],
    treatment: 'مضاد حيوي مناسب بعد فحص بول/زرع + دعم سوائل.',
    prevention: 'ماء كافٍ، حمية مناسبة، متابعة حصوات إن وجدت.',
    species: ['القطط', 'الكلاب'],
  },
  {
    id: 12,
    name: 'حصوات المسالك البولية',
    scientificName: 'Urolithiasis',
    type: 'مسالك بولية',
    severity: 'عالي',
    description: 'تشكّل حصوات قد يسبب انسداداً بولياً خطيراً خصوصاً في ذكور القطط.',
    symptoms: ['صعوبة تبول', 'محاولات متكررة', 'ألم/مواء', 'بول قليل أو معدوم'],
    treatment: 'علاج عاجل عند الانسداد + قسطرة/سوائل + حمية إذابة/جراحة حسب النوع.',
    prevention: 'حمية مخصصة + زيادة شرب الماء + متابعة دورية.',
    species: ['القطط', 'الكلاب'],
  },
  {
    id: 13,
    name: 'السكري',
    scientificName: 'Diabetes mellitus',
    type: 'استقلابي',
    severity: 'عالي',
    description: 'اضطراب في تنظيم السكر يتطلب متابعة دقيقة وحقن أنسولين غالباً.',
    symptoms: ['عطش شديد', 'تبول كثير', 'فقدان وزن', 'زيادة شهية أو خمول'],
    treatment: 'أنسولين + نظام غذائي + متابعة سكر دورية.',
    prevention: 'ضبط الوزن، فحوصات دورية خاصة لكبار السن.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 14,
    name: 'فرط نشاط الغدة الدرقية',
    scientificName: 'Feline hyperthyroidism',
    type: 'استقلابي',
    severity: 'متوسط',
    description: 'شائع في القطط الكبيرة ويسبب فقدان وزن مع شهية عالية واضطراباً بالقلب.',
    symptoms: ['فقدان وزن', 'شهية عالية', 'فرط نشاط', 'قيء أحياناً', 'عطش'],
    treatment: 'أدوية تنظيم الغدة/علاج باليود المشع/جراحة حسب تقييم الطبيب.',
    prevention: 'فحوصات دورية للقطط فوق 7 سنوات.',
    species: ['القطط'],
  },
  {
    id: 15,
    name: 'قصور الكلى المزمن',
    scientificName: 'Chronic kidney disease (CKD)',
    type: 'مزمن',
    severity: 'عالي',
    description: 'تدهور تدريجي بوظائف الكلى شائع في كبار السن خاصة القطط.',
    symptoms: ['عطش', 'تبول كثير', 'فقدان شهية', 'فقدان وزن', 'قيء'],
    treatment: 'حمية كلوية + سوائل + أدوية ضغط/فوسفات حسب الحالة.',
    prevention: 'ماء كافٍ، متابعة دورية، علاج مبكر للالتهابات.',
    species: ['القطط', 'الكلاب'],
  },
  {
    id: 16,
    name: 'الديدان المعوية',
    scientificName: 'Intestinal helminths',
    type: 'طفيلي',
    severity: 'متوسط',
    description: 'طفيليات معوية (أسطوانية/شريطية) تسبب اضطرابات هضمية ونقص وزن.',
    symptoms: ['إسهال', 'انتفاخ بطن', 'قيء', 'نقص وزن', 'حكة حول الشرج'],
    treatment: 'أدوية طفيليات مناسبة حسب النوع وجدول تكرار.',
    prevention: 'برنامج ديدان دوري، نظافة، منع أكل الفضلات.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 17,
    name: 'البراغيث',
    scientificName: 'Flea infestation',
    type: 'طفيلي',
    severity: 'متوسط',
    description: 'طفيليات خارجية تسبب حكة وقد تنقل الديدان وتسبب حساسية وبرودة دم.',
    symptoms: ['حكة شديدة', 'نقاط سوداء بالفراء', 'تساقط شعر', 'قروح'],
    treatment: 'مبيد براغيث آمن للحيوان + علاج البيئة + معالجة جميع الحيوانات بالمنزل.',
    prevention: 'وقاية شهرية، تنظيف المفروشات، متابعة منتظمة.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 18,
    name: 'القراد',
    scientificName: 'Tick infestation',
    type: 'طفيلي',
    severity: 'متوسط',
    description: 'قد ينقل أمراضاً خطيرة مثل بابيزيا وإيرليخيا ويزيد خطر فقر الدم.',
    symptoms: ['وجود قراد على الجلد', 'خمول', 'شحوب', 'حمّى أحياناً'],
    treatment: 'إزالة آمنة + أدوية وقائية/علاجية حسب الحاجة + فحوص دم عند الاشتباه.',
    prevention: 'وقاية منتظمة ضد القراد، تفقد الفراء بعد الخروج.',
    species: ['الكلاب'],
  },
  {
    id: 19,
    name: 'السعال الكلبي (التهاب القصبات المعدي)',
    scientificName: 'Canine infectious tracheobronchitis',
    type: 'تنفسي',
    severity: 'متوسط',
    description: 'عدوى تنفسية تسبب سعالا جافاً وقد تنتشر في التجمعات.',
    symptoms: ['سعال جاف', 'رشح', 'عطاس', 'خمول بسيط'],
    treatment: 'علاج داعم وقد تحتاج مضادات حسب الحالة + راحة وعزل.',
    prevention: 'لقاح السعال الكلبي في البيئات عالية الاختلاط، تجنب الاختلاط أثناء التفشي.',
    species: ['الكلاب'],
  },
  {
    id: 20,
    name: 'التهاب رئوي',
    scientificName: 'Pneumonia',
    type: 'تنفسي',
    severity: 'عالي',
    description: 'التهاب في الرئتين قد يكون بكتيرياً/استنشاقياً ويحتاج علاجاً سريعاً.',
    symptoms: ['سعال', 'صعوبة تنفس', 'حمّى', 'خمول', 'فقدان شهية'],
    treatment: 'مضادات + دعم أكسجين/سوائل حسب شدة الحالة.',
    prevention: 'علاج مبكر للعدوى، منع الاستنشاق أثناء الإطعام القسري.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 21,
    name: 'داء المقوسات',
    scientificName: 'Toxoplasmosis',
    type: 'طفيلي',
    severity: 'متوسط',
    description: 'عدوى طفيلية قد تسبب أعراضاً عصبية/تنفسية، وتهم خصوصاً الحوامل والبشر.',
    symptoms: ['خمول', 'حمّى', 'مشاكل تنفس', 'اضطراب عصبي (نادر)'],
    treatment: 'أدوية مضادة للطفيليات حسب الحالة وتقييم الطبيب.',
    prevention: 'نظافة صندوق الرمل، تجنب اللحم النيء، غسل اليدين.',
    species: ['القطط'],
  },
  {
    id: 22,
    name: 'التهاب ملتحمة العين',
    scientificName: 'Conjunctivitis',
    type: 'التهابي',
    severity: 'منخفض',
    description: 'التهاب شائع في العين بسبب حساسية/عدوى، وقد يسبب إفرازات واحمرار.',
    symptoms: ['احمرار', 'دموع/إفرازات', 'حكة بالعين', 'انغلاق جزئي'],
    treatment: 'قطرات مناسبة بعد فحص، وقد يلزم مضاد حيوي/مضاد حساسية.',
    prevention: 'تجنب المهيجات، علاج العدوى مبكراً.',
    species: ['القطط', 'الكلاب'],
  },
  {
    id: 23,
    name: 'الأنيميا (فقر الدم)',
    scientificName: 'Anemia',
    type: 'دم',
    severity: 'عالي',
    description: 'انخفاض كريات الدم قد ينتج عن طفيليات/نزيف/أمراض مزمنة.',
    symptoms: ['شحوب اللثة', 'خمول', 'تسارع تنفس/نبض', 'ضعف'],
    treatment: 'حسب السبب: علاج طفيليات/وقف نزيف/نقل دم عند الحاجة.',
    prevention: 'وقاية من القراد/البراغيث، فحوص دورية.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 24,
    name: 'الصرع/نوبات تشنج',
    scientificName: 'Epileptic seizures',
    type: 'عصبي',
    severity: 'عالي',
    description: 'نوبات قد تكون أولية أو بسبب سبب ثانوي وتحتاج تقييم عاجل خاصة عند تكرارها.',
    symptoms: ['تشنجات', 'فقدان وعي', 'سيلان لعاب', 'ارتباك بعد النوبة'],
    treatment: 'أدوية مضادة للتشنجات حسب التشخيص + فحوص للسبب.',
    prevention: 'متابعة منتظمة للحالات المزمنة، تجنب محفزات معروفة.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 25,
    name: 'تسمم الشوكولاتة',
    scientificName: 'Theobromine poisoning',
    type: 'تسمم',
    severity: 'عالي',
    description: 'الشوكولاتة سامة للكلاب وقد تسبب اضطراباً قلبياً وعصبياً.',
    symptoms: ['قيء', 'إسهال', 'تسارع نبض', 'رجفان', 'تشنجات'],
    treatment: 'تدخل بيطري عاجل (تحفيز قيء/فحم نشط/سوائل) حسب الوقت والكمية.',
    prevention: 'إبعاد الشوكولاتة والحلويات عن متناول الحيوانات.',
    species: ['الكلاب'],
  },
  {
    id: 26,
    name: 'تسمم البصل/الثوم',
    scientificName: 'Allium toxicosis',
    type: 'تسمم',
    severity: 'عالي',
    description: 'البصل والثوم قد يسببان تكسّر كريات الدم وحدوث أنيميا.',
    symptoms: ['خمول', 'قيء', 'شحوب', 'تنفس سريع', 'بول داكن أحياناً'],
    treatment: 'رعاية بيطرية حسب شدة الحالة وقد يلزم نقل دم.',
    prevention: 'تجنب إعطاء بقايا طعام تحتوي على بصل/ثوم.',
    species: ['القطط', 'الكلاب'],
  },
  {
    id: 27,
    name: 'التهاب الكبد',
    scientificName: 'Hepatitis',
    type: 'استقلابي',
    severity: 'عالي',
    description: 'التهاب أو تضرر في الكبد نتيجة عدوى/سموم/أسباب أخرى.',
    symptoms: ['قيء', 'خمول', 'اصفرار (يرقان)', 'فقدان شهية'],
    treatment: 'حسب السبب: سوائل، أدوية حماية كبد، علاج عدوى/سموم.',
    prevention: 'تجنب السموم، تطعيمات حسب المنطقة.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 28,
    name: 'التهاب الرحم القيحي (قيح الرحم)',
    scientificName: 'Pyometra',
    type: 'تناسل',
    severity: 'عالي',
    description: 'حالة خطيرة في إناث الكلاب/القطط غير المعقمة بعد فترة الشبق.',
    symptoms: ['خمول شديد', 'إفرازات مهبلية', 'عطش', 'قيء', 'حمّى'],
    treatment: 'عادةً جراحة عاجلة (تعقيم) + مضادات وسوائل.',
    prevention: 'تعقيم الإناث غير المخصصة للتربية.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 29,
    name: 'التهاب الغدة الثديية',
    scientificName: 'Mastitis',
    type: 'التهابي',
    severity: 'متوسط',
    description: 'التهاب في الغدد الثديية أثناء الرضاعة وقد يسبب ألماً وارتفاع حرارة.',
    symptoms: ['تورم/ألم بالثدي', 'إفرازات غير طبيعية', 'حمّى', 'رفض الرضاعة'],
    treatment: 'مضادات مناسبة + كمادات حسب إرشاد الطبيب + متابعة الجراء.',
    prevention: 'نظافة، مراقبة أثناء الرضاعة.',
    species: ['الكلاب', 'القطط'],
  },
  {
    id: 30,
    name: 'الطفيليات القلبية (الديدان القلبية)',
    scientificName: 'Dirofilaria immitis (Heartworm)',
    type: 'طفيلي',
    severity: 'عالي',
    description: 'طفيلي ينتقل عبر البعوض ويصيب القلب/الرئتين خاصة في الكلاب.',
    symptoms: ['سعال', 'تعب سريع', 'نقص وزن', 'ضيق تنفس'],
    treatment: 'علاج مخصص تحت إشراف بيطري وقد يكون طويل الأمد.',
    prevention: 'وقاية شهرية ضد الديدان القلبية + مكافحة البعوض.',
    species: ['الكلاب'],
    references: [
      { label: 'AHS - Heartworm Basics', url: 'https://www.heartwormsociety.org/pet-owner-resources/heartworm-basics' },
    ],
  },
];

// أمراض نادرة/متخصصة
export const RARE_DISEASES_AR: Disease[] = [
  {
    id: 101,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=600&fit=crop&q=80',
    name: 'داء اللشمانيا (الليشمانيا)',
    scientificName: 'Leishmania infantum',
    type: 'طفيلي',
    severity: 'متوسط',
    description: 'مرض طفيلي ينتقل عبر ذبابة الرمل ويؤثر على الجلد وأعضاء داخلية. قد يكون مزمناً.',
    symptoms: ['فقدان وزن', 'تساقط شعر', 'تضخم غدد لمفاوية', 'تقرحات جلدية', 'خمول'],
    treatment: 'علاج طفيلي طويل الأمد وفق الطبيب البيطري (يختلف حسب البروتوكول) مع متابعة دورية.',
    prevention: 'مكافحة الحشرات (طوق/قطرات)، تجنب التعرض لذبابة الرمل، فحص دوري.',
    species: ['الكلاب'],
    references: [
      { label: 'WHO - Leishmaniasis', url: 'https://www.who.int/news-room/fact-sheets/detail/leishmaniasis' },
    ],
  },
  {
    id: 102,
    image: 'https://images.unsplash.com/photo-1582737306564-e18b10874e07?w=800&h=600&fit=crop&q=80',
    name: 'داء البابيزيا',
    scientificName: 'Babesiosis',
    type: 'طفيلي',
    severity: 'عالي',
    description: 'مرض طفيلي ينتقل غالباً عبر القراد ويسبب تكسّر كريات الدم وفقر دم.',
    symptoms: ['حمّى', 'شحوب', 'خمول', 'بول داكن', 'فقدان شهية'],
    treatment: 'أدوية مضادة للطفيليات + دعم سوائل وقد يلزم نقل دم حسب الشدة.',
    prevention: 'وقاية قوية من القراد وفحص دوري بعد الخروج.',
    species: ['الكلاب'],
    references: [
      { label: 'Merck Vet Manual - Babesiosis', url: 'https://www.merckvetmanual.com/circulatory-system/blood-parasites/babesiosis' },
    ],
  },
  {
    id: 103,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop&q=80',
    name: 'داء إيرليخيا',
    scientificName: 'Ehrlichiosis',
    type: 'بكتيري',
    severity: 'عالي',
    description: 'عدوى تنتقل بالقراد وقد تؤثر على الصفائح الدموية وتسبب نزفاً أو خمولاً شديداً.',
    symptoms: ['حمّى', 'نزف/كدمات', 'خمول', 'ألم مفاصل', 'فقدان شهية'],
    treatment: 'مضاد حيوي مناسب (مثل دوكسيسيكلين) حسب وصف الطبيب + دعم عام.',
    prevention: 'وقاية من القراد، إزالة القراد سريعاً.',
    species: ['الكلاب'],
    references: [
      { label: 'Merck Vet Manual - Ehrlichiosis', url: 'https://www.merckvetmanual.com/circulatory-system/blood-parasites/ehrlichiosis' },
    ],
  },
  {
    id: 104,
    image: 'https://images.unsplash.com/photo-1524024973425-074bc935ef7a?w=800&h=600&fit=crop&q=80',
    name: 'حمّى Q (في المواشي)',
    scientificName: 'Coxiella burnetii infection',
    type: 'بكتيري',
    severity: 'متوسط',
    description: 'عدوى قد تصيب المواشي وتهم الصحة العامة. قد ترتبط بمشاكل إجهاض في بعض الحالات.',
    symptoms: ['قد تكون بلا أعراض', 'ضعف عام', 'مشاكل تناسلية في القطيع'],
    treatment: 'حسب سياسات المنطقة والإشراف البيطري للقطيع.',
    prevention: 'إدارة صحية للقطيع ونظافة، عزل حالات الإجهاض، استشارة بيطري مختص.',
    species: ['الأغنام', 'الماعز', 'الأبقار'],
    references: [
      { label: 'CDC - Q Fever', url: 'https://www.cdc.gov/qfever/' },
    ],
  },
  {
    id: 105,
    image: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&h=600&fit=crop&q=80',
    name: 'التهاب الرحم المعدي في الخيول',
    scientificName: 'Contagious equine metritis (CEM)',
    type: 'بكتيري',
    severity: 'متوسط',
    description: 'مرض تناسلي في الخيول يؤثر على الخصوبة ويتطلب إدارة بيطرية للقطيع/الإسطبل.',
    symptoms: ['قد تكون الفرس دون أعراض واضحة', 'إفرازات مهبلية أحياناً', 'انخفاض الخصوبة'],
    treatment: 'علاج موضعي/مضادات حسب البروتوكول البيطري وإجراءات حجر.',
    prevention: 'فحوصات تناسلية، حجر للحالات، إدارة تزاوج سليمة.',
    species: ['الخيول'],
  },
];
